//===-- python_token.hpp - Instruction class definition ---------*- C++ -*-===//
//
// Part of the Hubbart Project, under the MIT License.
// See https://mit-license.org/ for license information.
// SPDX-License-Identifier: MIT License
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Represents a Python Token generated by the Hubbart Lexer and consumed by the
/// Hubbart Parser.
///
//===----------------------------------------------------------------------===//

#ifndef __HUBBART_PYTHON_TOKEN_HPP
#define __HUBBART_PYTHON_TOKEN_HPP

#include <string>

#include "python_token_type.hpp"

/**
 * @brief The Hubbart representation of a Python Token.
 * 
 */
class PythonToken {
private:
    PythonTokenType type;
    std::string lexeme;
public:
    /**
     * @brief Construct a new Python Token object
     * 
     */
    PythonToken(const PythonTokenType &, const std::string &);

    /**
     * @brief Get the Type object
     * 
     * @return PythonTokenType 
     */
    PythonTokenType getType(void);

    /**
     * @brief Get the Lexeme string
     * 
     * @return std::string 
     */
    std::string getLexeme(void);
};


#endif